collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.8315412
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#301A24'
    - '#B11A42'
    - '#8A5B1B'
    - '#AD881F'
    - '#589FC0'
  rhythmicContrast: 1
layout_spectrum: 1
name: Isaac Arango Saad
