layout_spectrum: 1
name: Isaac Arango Saad
typography_spectrum: 0.8315412
color:
  brandStrength: 1
  saturation: 1
  brandColors:
    - '#301A24'
    - '#B11A42'
    - '#8A5B1B'
    - '#AD881F'
    - '#589FC0'
  lightness: 1
  rhythmicContrast: 1
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
