color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#252831'
    - '#31131B'
    - '#645C38'
    - '#43202B'
    - '#572B4C'
  lightness: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 1
typography_spectrum: 0.8315412
name: Isaac Arango Saad
