layout_spectrum: 1
typography_spectrum: 0.8315412
color:
  saturation: 0.8010753
  brandStrength: 1
  lightness: 0.8602151
  brandColors:
    - '#FDFDFD'
    - '#A6C3D3'
    - '#0D1925'
    - '#A3915F'
    - '#6D5F56'
  rhythmicContrast: 1
name: Isaac Arango Saad
