layout_spectrum: 1
typography_spectrum: 0.817032
color:
  lightness: 1
  brandStrength: 1
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#2F1B26'
    - '#551722'
    - '#63502D'
    - '#2E2F30'
    - '#802237'
name: ISAAC ARANGO SAAD
